### ISSUE TITLE
'Didn't find a name for constructor' Error on tags genratation

### ISSUE THREAD

**Issue by Ferroman** [mozilla/doctorjs#44]
Hi

I have tried to generate the tags using "jsctags ." command in folder with .js files, but I got an error:

```
$ jsctags .
Didn't find a name for constructor

/usr/local/bin/jsctags:195
                throw e;
                      ^
Error: Didn't find a name for constructor
    at errorWithCode (/usr/local/lib/cfa2/jscfa.js:157:11)
    at Array.toType (/usr/local/lib/cfa2/jscfa.js:1574:11)
    at /usr/local/lib/cfa2/jscfa.js:1994:18
    at Aval.forEachObj (/usr/local/lib/cfa2/jscfa.js:2020:5)
    at Aval.toType (/usr/local/lib/cfa2/jscfa.js:1993:8)
    at funToType (/usr/local/lib/cfa2/jscfa.js:3736:31)
    at getTags (/usr/local/lib/cfa2/jscfa.js:3786:24)
    at Object.interpret (/usr/local/lib/jsctags/ctags/interp.js:54:21)
    at Object.scan (/usr/local/lib/jsctags/ctags/index.js:104:16)
    at processPath (/usr/local/bin/jsctags:189:18)
```

My system info:

```
$ echo $NODE_PATH
/usr/local/lib/jsctags/:
```

```
$ node --version
v0.6.19
```

```
doctorjs$ git log -1
commit 96793072fb43cb0baca6025a187aeaf9f7cdfd79
Author: Dimitris Vardoulakis <dimvar@gmail.com>
Date:   Sat Apr 14 15:45:09 2012 -0400

    Bugfix for exports in commonJS mode.
```

**Comment by MarcinWieczorek** [comment]
Thank you @shinglyu for the patch, it works and should be merged with the master.
