### ISSUE TITLE
jsctags does not work with nodejs 0.10.0

### ISSUE THREAD

**Issue by sangwook-kim** [mozilla/doctorjs#52]
Hi. 
I'm on Ubuntu. and I found a problem yesterday.
Ubuntu package manager provides nodejs 0.6.x.
I'm trying grunt 0.4.\* and grunt 0.4.x needs nodejs >= 0.8.
So I've downloaded and built nodejs 0.10.x (which is official new stable version.)
# Then, jsctags has broke and issued some error message complaining about

Array.prototype.push called on null or undefined

/usr/local/bin/jsctags:195
                throw e;
                      ^
TypeError: Array.prototype.push called on null or undefined
    at Object.exports.Tags.Object.create.Trait.compose.Trait.add (/usr/local/lib/jsctags/ctags/index.js:71:30)
    at Object.exports.Tags.Object.create.Trait.compose.Trait.scan (/usr/local/lib/jsctags/ctags/index.js:105:14)
    at processPath (/usr/local/bin/jsctags:189:18)
    at Object.<anonymous> (/usr/local/bin/jsctags:207:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
#     at startup (node.js:119:16)

I figured a workaround for this situation.
1. sudo -H npm install -g n : Install 'n' to use as node version management tool.
2. sudo n 0.10.0 : to recognize 0.10.x that i've already installed
3. sudo n 0.8.22 : to install 0.8.x, which works fine for jsctags and grunt.

maybe you need to sudo n use 0.8.22 to make 0.8.22 default. I'm not quite familiar with 'n'.

and when you get "node -v" "0.8.22". All problem solved for me.

Still, I think it would be better for jsctags work with node 0.10.x.

Thank you.

**Comment by nameused** [comment]
it works. thanks.
